### PR TITLE
Support for ReadableStream body

### LINKED ISSUE #36: Support for streaming body via UNSIGNED_PAYLOAD
Scenario: 

Sending large post with byte array using ReadableStream for performance reasons.

Expected Behavior:

ReadableStream is sent to S3 via a streaming read, offering improved performance.

Actual Behavior:

Receive "body must be a string, ArrayBuffer or ArrayBufferView, unless you include the X-Amz-Content-Sha256 header"

Steps to reproduce:

```
  let { readable, writable } = new TransformStream();
  const arr = new Uint8Array([ 102,111,111,98,97,114 ])
  writeArrayToStream(arr, writable);
  const signed = await aws.sign(url, { method: 'PUT', headers, body: readable});
  const resp = await fetch(signed);
  return resp
```

Details:

Problem 1 - Cloning the request
In the signing flow, the request is cloned (https://github.com/mhart/aws4fetch/blob/master/src/main.js#L89) for signing, including the body. This is probably strike #1 for using ReadableStream, ideally there is no cloning of a large request.

Problem 2 - 

In the Canonical String generation, there is a call to get the hexBodyHash (https://github.com/mhart/aws4fetch/blob/master/src/main.js#L310). 
In the hexBodyHash method, it checks that the body is of type string or has a byteLength (like in an ArrayBuffer I think). A readable stream meets neither of those cases, so it throws the Error.

Proposed solution:

Add an option for unsigned payloads (see https://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-header-based-auth.html) by replacing the hexBodyHash with the literal string UNSIGNED-PAYLOAD. I didn't dig too far into this, but it looks like it may be an option on the node version of this (https://github.com/mhart/aws4/blob/master/aws4.js#L244)?

### PR DESCRIPTION
**Pull request by Manouchehri**
This is quite important for us folks using aws4fetch in a CF Worker in bundled billing mode.

Fixes #36

### CODE REVIEW

**Comment by Manouchehri** [comment]
For those who realllllly can't wait (like myself), here's a published fork: https://www.npmjs.com/package/@aimoda/aws4fetch

**Comment by mhart** [comment]
To be clear, you can set the `X-Amz-Content-Sha256` header to whatever you like (including `UNSIGNED-PAYLOAD`) – you don't need to use a fork of this library to do this.

**Comment by Manouchehri** [comment]
Agreed, I think this PR makes the behavior a bit more developer friendly. (I think most of us often use ReadableStreams because we _don't_ want to buffer everything into memory.)

**Comment by mhart** [comment]
I'm not convinced this works with every service though – in fact, I suspect it works with very few as, at least in the past, most services required fully hashed bodies. Happy to test it out though. Which services have you tested it on?

**Comment by Manouchehri** [comment]
I'm using it with Lambda Function URLs.

https://docs.aws.amazon.com/lambda/latest/dg/urls-invocation.html#urls-payloads

**Comment by mhart** [comment]
Right, that makes sense for that particular use case. But nearly every other AWS service uses fixed JSON/XML payloads as bodies, so using ReadableStreams will likely just get signature errors. I can test it out when I get some time, but I don't think this should go in as is – at the very least the documentation should be updated to highlight that users might get errors if they use streams.

**Comment by Manouchehri** [comment]
Nope, I am 100% wrong. It does _not_ work with Lambda Function URLs like I claimed. Not sure why I thought it was working.

**Comment by bcheung** [comment]
Hi @mhart  
I think I have a similar use case as @Manouchehri where my request body could be a `ReadableStream` and for context, I'm using a cloudflare worker to proxy requests to my lambda function url which requires IAM authorization.

This error thrown when the request body is a `ReadableStream`:
https://github.com/mhart/aws4fetch/blob/629b108747e066d1b93e8b72a4adbf2a4220db3b/src/main.js#L328-L330

I guess this makes sense as this check requires the payload to be signed.

However, I'm wondering if:
1. the only way to allow a `ReadableStream` request body is to provide the `X-Amz-Content-Sha256` header for signing? 
That would mean the client making a request to the proxy must provide a hash of the payload, and my proxy would then need to set that as the `X-Amz-Content-Sha256` header.
2. If that is the case, do you know of a reliable way to detect if the request body is a `ReadableStream`?
I see you have some logic here that might be doing something similar?
https://github.com/mhart/aws4fetch/blob/629b108747e066d1b93e8b72a4adbf2a4220db3b/src/main.js#L83-L89

Apologies if some of this is out of scope, but I'm very new to this whole signing concept and even the fact that the request body isn't just a simple string or object but could also be a `ReadableStream`, so I appreciate if you could help fill some knowledge gaps!

Also thanks for making this library!

**Comment by bcheung** [comment]
Ah appreciate the reply that's what I ended up doing

**Pull request closed without merging**
